//storing data inside of an object instead of an array is called DATA NORMALIZATION.
const SHOP_DATA = {
  hats: {
    id: 1,
    title: "Hats",
    routeName: "hats",
    items: [
      {
        id: 1,
        name: "Brown Brim",
        imageUrl: "https://i.ibb.co/ZYW3VTp/brown-brim.png",
        inCart: false,
        price: 25,
        details: [
          "Lorem ipsum dolor sit amet consectetur adipisicing elit.Perspiciatis, earum!",
          "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Beatae optio ipsum perspiciatis.",
          "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
          "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sapiente totam, hic delectus nisi doloribus numquam dolorem animi quidem itaque voluptate vel alias.",
        ],
      },
      {
        id: 2,
        name: "Blue Beanie",
        imageUrl: "https://i.ibb.co/ypkgK0X/blue-beanie.png",
        inCart: false,
        price: 18,
        details: [
          "Lorem ipsum dolor sit amet consectetur adipisicing elit.Perspiciatis, earum!",
          "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Beatae optio ipsum perspiciatis.",
          "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
          "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sapiente totam, hic delectus nisi doloribus numquam dolorem animi quidem itaque voluptate vel alias.",
        ],
      },
      {
        id: 3,
        name: "Brown Cowboy",
        imageUrl: "https://i.ibb.co/QdJwgmp/brown-cowboy.png",
        inCart: false,
        price: 35,
        details: [
          "Lorem ipsum dolor sit amet consectetur adipisicing elit.Perspiciatis, earum!",
          "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Beatae optio ipsum perspiciatis.",
          "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
          "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sapiente totam, hic delectus nisi doloribus numquam dolorem animi quidem itaque voluptate vel alias.",
        ],
      },
      {
        id: 4,
        name: "Grey Brim",
        imageUrl: "https://i.ibb.co/RjBLWxB/grey-brim.png",
        inCart: false,
        price: 25,
        details: [
          "Lorem ipsum dolor sit amet consectetur adipisicing elit.Perspiciatis, earum!",
          "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Beatae optio ipsum perspiciatis.",
          "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
          "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sapiente totam, hic delectus nisi doloribus numquam dolorem animi quidem itaque voluptate vel alias.",
        ],
      },
      {
        id: 5,
        name: "Green Beanie",
        imageUrl: "https://i.ibb.co/YTjW3vF/green-beanie.png",
        inCart: false,
        price: 18,
        details: [
          "Lorem ipsum dolor sit amet consectetur adipisicing elit.Perspiciatis, earum!",
          "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Beatae optio ipsum perspiciatis.",
          "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
          "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sapiente totam, hic delectus nisi doloribus numquam dolorem animi quidem itaque voluptate vel alias.",
        ],
      },
      {
        id: 6,
        name: "Palm Tree Cap",
        imageUrl: "https://i.ibb.co/rKBDvJX/palm-tree-cap.png",
        inCart: false,
        price: 14,
        details: [
          "Lorem ipsum dolor sit amet consectetur adipisicing elit.Perspiciatis, earum!",
          "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Beatae optio ipsum perspiciatis.",
          "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
          "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sapiente totam, hic delectus nisi doloribus numquam dolorem animi quidem itaque voluptate vel alias.",
        ],
      },
      {
        id: 7,
        name: "Red Beanie",
        imageUrl: "https://i.ibb.co/bLB646Z/red-beanie.png",
        inCart: false,
        price: 18,
        details: [
          "Lorem ipsum dolor sit amet consectetur adipisicing elit.Perspiciatis, earum!",
          "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Beatae optio ipsum perspiciatis.",
          "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
          "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sapiente totam, hic delectus nisi doloribus numquam dolorem animi quidem itaque voluptate vel alias.",
        ],
      },
      {
        id: 8,
        name: "Wolf Cap",
        imageUrl: "https://i.ibb.co/1f2nWMM/wolf-cap.png",
        inCart: false,
        price: 14,
        details: [
          "Lorem ipsum dolor sit amet consectetur adipisicing elit.Perspiciatis, earum!",
          "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Beatae optio ipsum perspiciatis.",
          "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
          "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sapiente totam, hic delectus nisi doloribus numquam dolorem animi quidem itaque voluptate vel alias.",
        ],
      },
      {
        id: 9,
        name: "Blue Snapback",
        imageUrl: "https://i.ibb.co/X2VJP2W/blue-snapback.png",
        inCart: false,
        price: 16,
        details: [
          "Lorem ipsum dolor sit amet consectetur adipisicing elit.Perspiciatis, earum!",
          "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Beatae optio ipsum perspiciatis.",
          "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
          "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sapiente totam, hic delectus nisi doloribus numquam dolorem animi quidem itaque voluptate vel alias.",
        ],
      },
    ],
  },
  sneakers: {
    id: 2,
    title: "Sneakers",
    routeName: "sneakers",
    items: [
      {
        id: 10,
        name: "Adidas NMD",
        imageUrl: "https://i.ibb.co/0s3pdnc/adidas-nmd.png",
        inCart: false,
        price: 220,
        details: [
          "Lorem ipsum dolor sit amet consectetur adipisicing elit.Perspiciatis, earum!",
          "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Beatae optio ipsum perspiciatis.",
          "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
          "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sapiente totam, hic delectus nisi doloribus numquam dolorem animi quidem itaque voluptate vel alias.",
        ],
      },
      {
        id: 11,
        name: "Adidas Yeezy",
        imageUrl: "https://i.ibb.co/dJbG1cT/yeezy.png",
        inCart: false,
        price: 280,
        details: [
          "Lorem ipsum dolor sit amet consectetur adipisicing elit.Perspiciatis, earum!",
          "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Beatae optio ipsum perspiciatis.",
          "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
          "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sapiente totam, hic delectus nisi doloribus numquam dolorem animi quidem itaque voluptate vel alias.",
        ],
      },
      {
        id: 12,
        name: "Black Converse",
        imageUrl: "https://i.ibb.co/bPmVXyP/black-converse.png",
        inCart: false,
        price: 110,
        details: [
          "Lorem ipsum dolor sit amet consectetur adipisicing elit.Perspiciatis, earum!",
          "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Beatae optio ipsum perspiciatis.",
          "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
          "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sapiente totam, hic delectus nisi doloribus numquam dolorem animi quidem itaque voluptate vel alias.",
        ],
      },
      {
        id: 13,
        name: "Nike White AirForce",
        imageUrl: "https://i.ibb.co/1RcFPk0/white-nike-high-tops.png",
        inCart: false,
        price: 160,
        details: [
          "Lorem ipsum dolor sit amet consectetur adipisicing elit.Perspiciatis, earum!",
          "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Beatae optio ipsum perspiciatis.",
          "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
          "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sapiente totam, hic delectus nisi doloribus numquam dolorem animi quidem itaque voluptate vel alias.",
        ],
      },
      {
        id: 14,
        name: "Nike Red High Tops",
        imageUrl: "https://i.ibb.co/QcvzydB/nikes-red.png",
        inCart: false,
        price: 160,
        details: [
          "Lorem ipsum dolor sit amet consectetur adipisicing elit.Perspiciatis, earum!",
          "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Beatae optio ipsum perspiciatis.",
          "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
          "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sapiente totam, hic delectus nisi doloribus numquam dolorem animi quidem itaque voluptate vel alias.",
        ],
      },
      {
        id: 15,
        name: "Nike Brown High Tops",
        imageUrl: "https://i.ibb.co/fMTV342/nike-brown.png",
        inCart: false,
        price: 160,
        details: [
          "Lorem ipsum dolor sit amet consectetur adipisicing elit.Perspiciatis, earum!",
          "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Beatae optio ipsum perspiciatis.",
          "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
          "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sapiente totam, hic delectus nisi doloribus numquam dolorem animi quidem itaque voluptate vel alias.",
        ],
      },
      {
        id: 16,
        name: "Air Jordan Limited",
        imageUrl: "https://i.ibb.co/w4k6Ws9/nike-funky.png",
        inCart: false,
        price: 190,
        details: [
          "Lorem ipsum dolor sit amet consectetur adipisicing elit.Perspiciatis, earum!",
          "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Beatae optio ipsum perspiciatis.",
          "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
          "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sapiente totam, hic delectus nisi doloribus numquam dolorem animi quidem itaque voluptate vel alias.",
        ],
      },
      {
        id: 17,
        name: "Timberlands",
        imageUrl: "https://i.ibb.co/Mhh6wBg/timberlands.png",
        inCart: false,
        price: 200,
        details: [
          "Lorem ipsum dolor sit amet consectetur adipisicing elit.Perspiciatis, earum!",
          "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Beatae optio ipsum perspiciatis.",
          "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
          "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sapiente totam, hic delectus nisi doloribus numquam dolorem animi quidem itaque voluptate vel alias.",
        ],
      },
    ],
  },
  jackets: {
    id: 3,
    title: "Jackets",
    routeName: "jackets",
    items: [
      {
        id: 18,
        name: "Black Jean Shearling",
        imageUrl: "https://i.ibb.co/XzcwL5s/black-shearling.png",
        inCart: false,
        price: 125,
        details: [
          "Lorem ipsum dolor sit amet consectetur adipisicing elit.Perspiciatis, earum!",
          "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Beatae optio ipsum perspiciatis.",
          "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
          "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sapiente totam, hic delectus nisi doloribus numquam dolorem animi quidem itaque voluptate vel alias.",
        ],
      },
      {
        id: 19,
        name: "Blue Jean Jacket",
        imageUrl: "https://i.ibb.co/mJS6vz0/blue-jean-jacket.png",
        inCart: false,
        price: 90,
        details: [
          "Lorem ipsum dolor sit amet consectetur adipisicing elit.Perspiciatis, earum!",
          "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Beatae optio ipsum perspiciatis.",
          "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
          "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sapiente totam, hic delectus nisi doloribus numquam dolorem animi quidem itaque voluptate vel alias.",
        ],
      },
      {
        id: 20,
        name: "Grey Jean Jacket",
        imageUrl: "https://i.ibb.co/N71k1ML/grey-jean-jacket.png",
        inCart: false,
        price: 90,
        details: [
          "Lorem ipsum dolor sit amet consectetur adipisicing elit.Perspiciatis, earum!",
          "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Beatae optio ipsum perspiciatis.",
          "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
          "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sapiente totam, hic delectus nisi doloribus numquam dolorem animi quidem itaque voluptate vel alias.",
        ],
      },
      {
        id: 21,
        name: "Brown Shearling",
        imageUrl: "https://i.ibb.co/s96FpdP/brown-shearling.png",
        inCart: false,
        price: 165,
        details: [
          "Lorem ipsum dolor sit amet consectetur adipisicing elit.Perspiciatis, earum!",
          "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Beatae optio ipsum perspiciatis.",
          "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
          "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sapiente totam, hic delectus nisi doloribus numquam dolorem animi quidem itaque voluptate vel alias.",
        ],
      },
      {
        id: 22,
        name: "Tan Trench",
        imageUrl: "https://i.ibb.co/M6hHc3F/brown-trench.png",
        inCart: false,
        price: 185,
        details: [
          "Lorem ipsum dolor sit amet consectetur adipisicing elit.Perspiciatis, earum!",
          "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Beatae optio ipsum perspiciatis.",
          "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
          "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sapiente totam, hic delectus nisi doloribus numquam dolorem animi quidem itaque voluptate vel alias.",
        ],
      },
    ],
  },
  womens: {
    id: 4,
    title: "Womens",
    routeName: "womens",
    items: [
      {
        id: 23,
        name: "Blue Tanktop",
        imageUrl: "https://i.ibb.co/7CQVJNm/blue-tank.png",
        inCart: false,
        price: 25,
        details: [
          "Lorem ipsum dolor sit amet consectetur adipisicing elit.Perspiciatis, earum!",
          "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Beatae optio ipsum perspiciatis.",
          "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
          "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sapiente totam, hic delectus nisi doloribus numquam dolorem animi quidem itaque voluptate vel alias.",
        ],
      },
      {
        id: 24,
        name: "Floral Blouse",
        imageUrl: "https://i.ibb.co/4W2DGKm/floral-blouse.png",
        inCart: false,
        price: 20,
        details: [
          "Lorem ipsum dolor sit amet consectetur adipisicing elit.Perspiciatis, earum!",
          "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Beatae optio ipsum perspiciatis.",
          "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
          "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sapiente totam, hic delectus nisi doloribus numquam dolorem animi quidem itaque voluptate vel alias.",
        ],
      },
      {
        id: 25,
        name: "Floral Dress",
        imageUrl: "https://i.ibb.co/KV18Ysr/floral-skirt.png",
        inCart: false,
        price: 80,
        details: [
          "Lorem ipsum dolor sit amet consectetur adipisicing elit.Perspiciatis, earum!",
          "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Beatae optio ipsum perspiciatis.",
          "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
          "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sapiente totam, hic delectus nisi doloribus numquam dolorem animi quidem itaque voluptate vel alias.",
        ],
      },
      {
        id: 26,
        name: "Red Dots Dress",
        imageUrl: "https://i.ibb.co/N3BN1bh/red-polka-dot-dress.png",
        inCart: false,
        price: 80,
        details: [
          "Lorem ipsum dolor sit amet consectetur adipisicing elit.Perspiciatis, earum!",
          "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Beatae optio ipsum perspiciatis.",
          "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
          "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sapiente totam, hic delectus nisi doloribus numquam dolorem animi quidem itaque voluptate vel alias.",
        ],
      },
      {
        id: 27,
        name: "Striped Sweater",
        imageUrl: "https://i.ibb.co/KmSkMbH/striped-sweater.png",
        inCart: false,
        price: 45,
        details: [
          "Lorem ipsum dolor sit amet consectetur adipisicing elit.Perspiciatis, earum!",
          "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Beatae optio ipsum perspiciatis.",
          "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
          "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sapiente totam, hic delectus nisi doloribus numquam dolorem animi quidem itaque voluptate vel alias.",
        ],
      },
      {
        id: 28,
        name: "Yellow Track Suit",
        imageUrl: "https://i.ibb.co/v1cvwNf/yellow-track-suit.png",
        inCart: false,
        price: 135,
        details: [
          "Lorem ipsum dolor sit amet consectetur adipisicing elit.Perspiciatis, earum!",
          "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Beatae optio ipsum perspiciatis.",
          "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
          "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sapiente totam, hic delectus nisi doloribus numquam dolorem animi quidem itaque voluptate vel alias.",
        ],
      },
      {
        id: 29,
        name: "White Blouse",
        imageUrl: "https://i.ibb.co/qBcrsJg/white-vest.png",
        inCart: false,
        price: 20,
        details: [
          "Lorem ipsum dolor sit amet consectetur adipisicing elit.Perspiciatis, earum!",
          "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Beatae optio ipsum perspiciatis.",
          "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
          "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sapiente totam, hic delectus nisi doloribus numquam dolorem animi quidem itaque voluptate vel alias.",
        ],
      },
    ],
  },
  mens: {
    id: 5,
    title: "Mens",
    routeName: "mens",
    items: [
      {
        id: 30,
        name: "Camo Down Vest",
        imageUrl: "https://i.ibb.co/xJS0T3Y/camo-vest.png",
        inCart: false,
        price: 325,
        details: [
          "Lorem ipsum dolor sit amet consectetur adipisicing elit.Perspiciatis, earum!",
          "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Beatae optio ipsum perspiciatis.",
          "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
          "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sapiente totam, hic delectus nisi doloribus numquam dolorem animi quidem itaque voluptate vel alias.",
        ],
      },
      {
        id: 31,
        name: "Floral T-shirt",
        imageUrl: "https://i.ibb.co/qMQ75QZ/floral-shirt.png",
        inCart: false,
        price: 20,
        details: [
          "Lorem ipsum dolor sit amet consectetur adipisicing elit.Perspiciatis, earum!",
          "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Beatae optio ipsum perspiciatis.",
          "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
          "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sapiente totam, hic delectus nisi doloribus numquam dolorem animi quidem itaque voluptate vel alias.",
        ],
      },
      {
        id: 32,
        name: "Black & White Longsleeve",
        imageUrl: "https://i.ibb.co/55z32tw/long-sleeve.png",
        inCart: false,
        price: 25,
        details: [
          "Lorem ipsum dolor sit amet consectetur adipisicing elit.Perspiciatis, earum!",
          "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Beatae optio ipsum perspiciatis.",
          "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
          "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sapiente totam, hic delectus nisi doloribus numquam dolorem animi quidem itaque voluptate vel alias.",
        ],
      },
      {
        id: 33,
        name: "Pink T-shirt",
        imageUrl: "https://i.ibb.co/RvwnBL8/pink-shirt.png",
        inCart: false,
        price: 25,
        details: [
          "Lorem ipsum dolor sit amet consectetur adipisicing elit.Perspiciatis, earum!",
          "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Beatae optio ipsum perspiciatis.",
          "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
          "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sapiente totam, hic delectus nisi doloribus numquam dolorem animi quidem itaque voluptate vel alias.",
        ],
      },
      {
        id: 34,
        name: "Jean Long Sleeve",
        imageUrl: "https://i.ibb.co/VpW4x5t/roll-up-jean-shirt.png",
        inCart: false,
        price: 40,
        details: [
          "Lorem ipsum dolor sit amet consectetur adipisicing elit.Perspiciatis, earum!",
          "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Beatae optio ipsum perspiciatis.",
          "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
          "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sapiente totam, hic delectus nisi doloribus numquam dolorem animi quidem itaque voluptate vel alias.",
        ],
      },
      {
        id: 35,
        name: "Burgundy T-shirt",
        imageUrl: "https://i.ibb.co/mh3VM1f/polka-dot-shirt.png",
        inCart: false,
        price: 25,
        details: [
          "Lorem ipsum dolor sit amet consectetur adipisicing elit.Perspiciatis, earum!",
          "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Beatae optio ipsum perspiciatis.",
          "Lorem ipsum, dolor sit amet consectetur adipisicing elit.",
          "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sapiente totam, hic delectus nisi doloribus numquam dolorem animi quidem itaque voluptate vel alias.",
        ],
      },
    ],
  },
};

// export default SHOP_DATA;
